### ISSUE TITLE
Broken avatar URL

### ISSUE THREAD

**Issue by rofe** [adobe/helix-theblog-importer#26]
Assuming it's an importer problem: the avatar URL here has a funny `.bin` extension and the image is broken on all posts by this author. Haven't seen other broken ones so far...

https://staging--theblog--adobe.hlx.page/en/authors/adobe-communications-team.html

**Comment by tripodsan** [comment]
that's probably my bad as well....

**Comment by tripodsan** [comment]
should be fixed now.
