### ISSUE TITLE
superfluous updates to product md files

### ISSUE THREAD

**Issue by rofe** [adobe/helix-theblog-importer#3]
The importer seems to be modifying product (and topic) `.md` files in SharePoint a lot:
![Screenshot 2020-03-23 at 23 20 28](https://user-images.githubusercontent.com/1609742/77368743-3104b680-6d5d-11ea-97d5-e654233c4efc.png)

I think we should avoid that, unless we really need to change something.

**Comment by kptdobe** [comment]
Yes, no check is made, just override whatever is there.
As long as theblog.adobe.com is the master, I would override so that we can any update. Once helix site becomes the master, we should only add new ones and not override anymore.
This is valide for products, authors, topics and posts.

**Comment by kptdobe** [comment]
Re-opening this one. At one point, we'll have to run complete full re-import. Deciding to override or not should be a capability to enable or not depending on the context, mainly to speed up the process in case of a large import.
