### ISSUE TITLE
inline elements lose spaces

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-theblog-importer#34]
https://theblog-adobe.hlx.page/en/drafts/migrated/2020/04/14/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19.html

Many spaces are missing. Source DOM contains spans where space is trimmed.

**Comment by kptdobe** [comment]
The issue is coming from: https://github.com/rehypejs/rehype-minify/issues/30

**Comment by davidnuescheler** [comment]
i think this has improved very much, i still found an occurence here:

https://theblog.adobe.com/financial-services-require-artists-touch/

vs. 

https://blog.adobe.com/en/drafts/migrated/2020/06/01/financial-services-require-artists-touch.html 

see at the very bottom

**Comment by kptdobe** [comment]
First, the `rehype-minify` issue has been fixed, I still need to integrate properly the fix.

And yes, what you describe is the `_emphasis that ends with a space _`.

I think now this is a bug in our pipeline: Github and VSCode markdown preview can deal with it properly!

**Comment by kptdobe** [comment]
No, wrong assumption: it works because there is another emphasis to close the sentence:

`_emphasis _test_._` in that case GitHub and VSCode parser is smarter than ours.

**Comment by kptdobe** [comment]
Now importer moves the leading and trailing spaces outside some of the inline elements. This full fixes this issue.

**Comment by kptdobe** [comment]
Last one fixed with https://github.com/adobe/helix-theblog-importer/pull/55.
