### ISSUE TITLE
superfluous comments / replies after import

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-theblog-importer#4]
i seems that depending on the post there is a section about comments / replies at the end of the `.md`

see:
https://theblog.helix-demo.xyz/en/archive/2020/your-tutorial-resource-guide-to-photography-editing.html

i think this is a section that we probably shouldn't import.

**Comment by kptdobe** [comment]
No clue how / why this author added the social stuff. This is probably unique...
