### ISSUE TITLE
Trends Research should be Trends & Research

### ISSUE THREAD

**Issue by rofe** [adobe/helix-theblog-importer#61]
According to the link in the top navigation, the category's name is "Trends & Research", not "Trends Research". This error stems from the mapping document where the ampersand has been omitted.

**Comment by kptdobe** [comment]
I fixed the mapping table. The content will be updated during the next import (next Wednesday ?)

**Comment by rofe** [comment]
I think we should re-import tomorrow so we're ready to move everything to /en/publish first thing on Wednesday.

**Comment by kptdobe** [comment]
Done with today's re-import.
