### ISSUE TITLE
embeds not being imported properly

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-theblog-importer#76]
When importing from the original blog, we search iframes for the src: 
https://github.com/adobe/helix-theblog-importer/blob/b19ace2424399d68ccab30ec169b9360f1b811f2/src/index.js#L50-L121

The problem is these links don't work with our embed services; what we need is link to the original content not the link given in the src attribute of an <iframe>. 

For example, these link cannot be embedded properly by Iframely but have been extracted during an import. You can check them at https://iframely.com/embed/: 

https://embed.spotify.com/?uri=spotify4gzpq5DPGxSnKTe4SA8HAU

https://www.linkedin.com/video/embed/live/urn:li:ugcPost:6666809526391570432

https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F673363193&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true

@trieloff  @kptdobe do you think this should be a helix-embed issue? I was thinking maybe we can make helix-embed more robust to these kinds of links.

**Comment by trieloff** [comment]
I'd see most importers as one-off scripts, so adding the workaround in helix-embed would be the more durable fix.
